# blacklist
branches:
  except:
    - /^1.*$/

language: php
php:
  - 5.5.9
  - 5.6
before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
script:
  - phpunit
  - bash ./phpcs.sh